import { fn } from "@storybook/test"

import OccupationsList from "./OccupationsList"

const mockedOccupations = [
  {
    object: "Occupation",
    stdCode: "OCC0120A",
    name: "Digital support technician - Digital Applications Technician (DAT) ",
    status: 1,
    statusName: "Approved occupation",
    level: 3,
    versionNo: "1.1",
    summary:
      "<p>This occupation is found in organisations, large and small, in all sectors, and within public, private and voluntary organisations. Organisations of all types are increasing applying digital technologies across all their business functions to maximise productivity. The demand for people who can support and implement these digital operations and digital change projects is increasing. Organisations of all types are increasingly supporting their service users though online and digital channels. Organisations are developing omni-channel approaches to meeting customer needs to deflect telephone and face-to-face contacts and so reduce costs.</p>\n<p>The broad purpose of a Digital Support Technician is to maximise the effective use of digital office technologies, productivity software and digital communications. These will include collaborative technologies, and digital information systems.</p>\n<p>A Digital Support Technician will select one of the following two options.</p>\n<p>A Digital Applications Technician (DAT) helps their organisation and its internal users to maximise the use of digital technologies. They help organisations adapt to and exploit changes in technology to meet objectives and maximise efficiency. They ensure effective use of digital office technologies, productivity software, digital communications, including collaborative technologies, and digital information systems.</p>\n<p>A Digital Service Technician (DST) supports external customers and clients through a wide variety of digital channels. A DST helps them access and receive services and provides coaching and support to them in their use of the digital systems. A DST will support external customers and clients to complete and submit data remotely. They will help them to diagnose and resolve problems with their access to and use of digital tools.</p>\n<p>In their daily work, Digital Support Technicians interact with a wide variety of internal or external users of digital systems. They will communicate through digital channels, by phone and/or face to face. Digital Support Technicians work under general direction, using discretion in identifying and dealing with complex issues. They receive clear instructions and have their work reviewed at frequent milestones and determine when issues should be escalated to a higherlevel Digital Support Technicians interact with and influence others, having workinglevelcontact with colleagues or customers. They may supervise others or make decisions which impact the work assigned to others or to other phases of projects. A Digital Support Technician plans, schedules and monitors their own work within limited deadlines and according to relevant law, standards and procedures.</p>\n<p>Digital Applications Technicians (DAT) devise digital productivity solutions and roll them out in the organisation. They work as digital champions, training and supporting colleagues to make the best use of digital tools and diagnose problems. They provide internal end-user application support. The DAT may also assist with digital operations and digital change projects.</p>\n<p>Digital Service Technicians (DST) help customers and clients register for and access data,productsand services through online and digital channels. This can be as part of a sales or customer service process. They support and coach external users in their use of these digital systems. They diagnose and resolve external users’ digital problems with accessing and using digital tools. A DST also advises on related hardware and software problems. They use software packages and tools such as collaborative technologies, to interface effectively with external end-users. They will use a variety of digital channels to maximise effective external user support and to resolve external end-user problems. A DST will use and maintain information systems such as Customer Relationship Management tools to manage service delivery, improve user experience and increase efficiency.</p>\n<p> </p>",
    overview:
      "Maximising the effective use of digital office technologies, productivity software and digital communications in organisations.",
    mapHierarchy: {
      routeId: 7,
      routeName: "Digital",
      routeSequence: 6,
      pathwayId: 57,
      pathwayName: "Digital Support and Services",
      clusterGroupId: 32,
      clusterId: 187,
      clusterName: "IT support and services technician",
      technicalLevel: 1,
      technicalLevelName: "Technical",
      pathwaySequence: 0,
      clusterGroupSequence: 0,
      clusterSeqeunce: 0,
    },
    products: [
      {
        object: "Product",
        name: "Digital support technician - Digital Applications Technician (DAT) ",
        level: 3,
        status: 1,
        statusName: "Approved for delivery",
        type: 1,
        typeName: "Apprenticeship",
        careerStarter: true,
        productCode: "ST0120",
        royal: false,
      },
      {
        object: "Product",
        name: "Digital support services - Digital support",
        level: 3,
        type: 3,
        typeName: "TLevel",
        careerStarter: false,
        productCode: "TL0007d",
      },
    ],
    statusLastUpdated: "2019-04-11",
  },
  {
    object: "Occupation",
    stdCode: "OCC0120B",
    name: "Digital support technician - Digital Service Technician (DST) ",
    status: 1,
    statusName: "Approved occupation",
    level: 3,
    versionNo: "1.1",
    summary:
      "<p>This occupation is found in organisations, large and small, in all sectors, and within public, private and voluntary organisations. Organisations of all types are increasing applying digital technologies across all their business functions to maximise productivity. The demand for people who can support and implement these digital operations and digital change projects is increasing. Organisations of all types are increasingly supporting their service users though online and digital channels. Organisations are developing omni-channel approaches to meeting customer needs to deflect telephone and face-to-face contacts and so reduce costs.</p>\n<p>The broad purpose of a Digital Support Technician is to maximise the effective use of digital office technologies, productivity software and digital communications. These will include collaborative technologies, and digital information systems.</p>\n<p>A Digital Support Technician will select one of the following two options.</p>\n<p>A Digital Applications Technician (DAT) helps their organisation and its internal users to maximise the use of digital technologies. They help organisations adapt to and exploit changes in technology to meet objectives and maximise efficiency. They ensure effective use of digital office technologies, productivity software, digital communications, including collaborative technologies, and digital information systems.</p>\n<p>A Digital Service Technician (DST) supports external customers and clients through a wide variety of digital channels. A DST helps them access and receive services and provides coaching and support to them in their use of the digital systems. A DST will support external customers and clients to complete and submit data remotely. They will help them to diagnose and resolve problems with their access to and use of digital tools.</p>\n<p>In their daily work, Digital Support Technicians interact with a wide variety of internal or external users of digital systems. They will communicate through digital channels, by phone and/or face to face. Digital Support Technicians work under general direction, using discretion in identifying and dealing with complex issues. They receive clear instructions and have their work reviewed at frequent milestones and determine when issues should be escalated to a higherlevel Digital Support Technicians interact with and influence others, having workinglevelcontact with colleagues or customers. They may supervise others or make decisions which impact the work assigned to others or to other phases of projects. A Digital Support Technician plans, schedules and monitors their own work within limited deadlines and according to relevant law, standards and procedures.</p>\n<p>Digital Applications Technicians (DAT) devise digital productivity solutions and roll them out in the organisation. They work as digital champions, training and supporting colleagues to make the best use of digital tools and diagnose problems. They provide internal end-user application support. The DAT may also assist with digital operations and digital change projects.</p>\n<p>Digital Service Technicians (DST) help customers and clients register for and access data, products and services through online and digital channels. This can be as part of a sales or customer service process. They support and coach external users in their use of these digital systems. They diagnose and resolve external users’ digital problems with accessing and using digital tools. A DST also advises on related hardware and software problems. They use software packages and tools such as collaborative technologies, to interface effectively with external end-users. They will use a variety of digital channels to maximise effective external user support and to resolve external end-user problems. A DST will use and maintain information systems such as Customer Relationship Management tools to manage service delivery, improve user experience and increase efficiency.</p>\n<p> </p>",
    overview:
      "Maximising the effective use of digital office technologies, productivity software and digital communications in organisations.",
    mapHierarchy: {
      routeId: 7,
      routeName: "Digital",
      routeSequence: 6,
      pathwayId: 57,
      pathwayName: "Digital Support and Services",
      clusterGroupId: 32,
      clusterId: 187,
      clusterName: "IT support and services technician",
      technicalLevel: 1,
      technicalLevelName: "Technical",
      pathwaySequence: 0,
      clusterGroupSequence: 0,
      clusterSeqeunce: 0,
    },
    products: [
      {
        object: "Product",
        name: "Digital support technician - Digital Service Technician (DST) ",
        level: 3,
        status: 1,
        statusName: "Approved for delivery",
        type: 1,
        typeName: "Apprenticeship",
        careerStarter: true,
        productCode: "ST0120",
        royal: false,
      },
      {
        object: "Product",
        name: "Digital support services - Digital support",
        level: 3,
        type: 3,
        typeName: "TLevel",
        careerStarter: false,
        productCode: "TL0007d",
      },
    ],
    statusLastUpdated: "2019-04-11",
  },
  {
    object: "Occupation",
    stdCode: "OCC0482C",
    name: "Digital and technology solutions specialist - Digital Business and Enterprise Systems Architecture Specialist",
    status: 1,
    statusName: "Approved occupation",
    level: 7,
    versionNo: "1.0",
    summary:
      "<p>A Digital &amp; Technology Solutions Specialist maintains digital and technology strategies through technology leadership; investigating, identifying and implementing technological strategic solutions. They direct digital technology provision by studying organisation goals, strategies, and practices and delivering and supporting strategic plans for implementing digital technologies. They are confident, competent and capable individuals able to apply leadership and change management skills to operate in a range of digital and technology related specialist roles.</p>",
    overview:
      "Investigating, identifying and implementing technological strategic solutions.",
    mapHierarchy: {
      routeId: 7,
      routeName: "Digital",
      routeSequence: 6,
      pathwayId: 58,
      pathwayName: "Digital Business Services",
      clusterGroupId: 37,
      clusterId: 235,
      clusterName: "Digital solutions professional",
      technicalLevel: 3,
      technicalLevelName: "Professional",
      pathwaySequence: 2,
      clusterGroupSequence: 0,
      clusterSeqeunce: 2,
    },
    products: [
      {
        object: "Product",
        name: "Digital and technology solutions specialist (integrated degree) - Digital Business and Enterprise Systems Architecture Specialist",
        level: 7,
        status: 1,
        statusName: "Approved for delivery",
        type: 1,
        typeName: "Apprenticeship",
        careerStarter: false,
        productCode: "ST0482",
        royal: false,
      },
    ],
    statusLastUpdated: "2018-08-07",
  },
  {
    object: "Occupation",
    stdCode: "OCC0482D",
    name: "Digital and technology solutions specialist - IT / Digital Futures Management Specialist",
    status: 1,
    statusName: "Approved occupation",
    level: 7,
    versionNo: "1.0",
    summary:
      "<p>A Digital &amp; Technology Solutions Specialist maintains digital and technology strategies through technology leadership; investigating, identifying and implementing technological strategic solutions. They direct digital technology provision by studying organisation goals, strategies, and practices and delivering and supporting strategic plans for implementing digital technologies. They are confident, competent and capable individuals able to apply leadership and change management skills to operate in a range of digital and technology related specialist roles.</p>",
    overview:
      "Investigating, identifying and implementing technological strategic solutions.",
    mapHierarchy: {
      routeId: 7,
      routeName: "Digital",
      routeSequence: 6,
      pathwayId: 58,
      pathwayName: "Digital Business Services",
      clusterGroupId: 37,
      clusterId: 235,
      clusterName: "Digital solutions professional",
      technicalLevel: 3,
      technicalLevelName: "Professional",
      pathwaySequence: 2,
      clusterGroupSequence: 0,
      clusterSeqeunce: 2,
    },
    products: [
      {
        object: "Product",
        name: "Digital and technology solutions specialist (integrated degree) - IT / Digital Futures Management Specialist",
        level: 7,
        status: 1,
        statusName: "Approved for delivery",
        type: 1,
        typeName: "Apprenticeship",
        careerStarter: false,
        productCode: "ST0482",
        royal: false,
      },
    ],
    statusLastUpdated: "2018-08-07",
  },
]

export default {
  title: "Occupations List",
  component: OccupationsList,
  args: {
    occupationsArray: mockedOccupations,
    eventHandler: fn(),
  },
}

export const OccupationsListWithResults = {}
