name: Cypress
on:
  pull_request:
  push:
    branches:
      - dev
      - main
jobs:
  e2e:
    name: End to End tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        working-directory: frontend
        run: npm install
      - name: Run E2E tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          working-directory: frontend
          wait-on: "http://localhost:3000"
          install: false
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
