name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - "dev"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        working-directory: frontend
        run: npm run build-storybook

      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          path: frontend/storybook-static
          checkout: false
